# Generated by Django 6.0 on 2026-01-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="original_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
